[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cavmir"
version = "0.1.0"
description = "Concept Activation Vectors in Music Information Retrieval."
authors = [
    { name = "Eylül Bektur", email = "cavmir@cyanite.ai" },
    { name = "Roman Gebhardt", email = "cavmir@cyanite.ai" },
    { name = "Arne Kuhle", email = "cavmir@cyanite.ai" }
]
license = { file = "LICENSE" }
dependencies = [
    "numpy==2.1.3",
    "transformers==4.47.1",
    "torch==2.6.0",
    "torchaudio==2.6.0",
    "librosa==0.10.2.post1",
    "soundfile==0.13.1",
    "matplotlib==3.10.1",
    "seaborn==0.13.2",
    "muq==0.1.0",
    "ipython==9.5.0",
]
requires-python = ">=3.9"

[project.optional-dependencies]
dev = ["pytest", "black", "ruff"] 

[project.urls]
Homepage = "https://github.com/WhoCares96/CAV-MIR"
Repository = "https://github.com/WhoCares96/CAV-MIR"

[tool.setuptools.packages.find]
where = ["."]
