[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cavmir"
version = "0.1.0"
description = "Concept Activation Vectors in Music Information Retrieval."
readme = "README.md"
authors = [
    { name = "Eylül Bektur", email = "example@mail.com" },
    { name = "Roman Gebhardt", email = "example@mail.com" },
    { name = "Arne Kuhle", email = "arne@cyanite.ai" }
]
license = { file = "LICENSE" }
dependencies = [
    "numpy==2.1.3",
    "transformers==4.47.1",
    "torch",
    "torchaudio",
    "nnAudio",
    "soundfile",
    "librosa",
    "webdataset"
]
requires-python = ">=3.9"

[project.optional-dependencies]
dev = ["pytest", "black", "ruff"] 

[project.urls]
Homepage = "https://github.com/WhoCares96/CAV-MIR"
Repository = "https://github.com/WhoCares96/CAV-MIR"

[tool.setuptools.packages.find]
where = ["."]
